const STORAGE_KEY = "happyHourVenues";
const SEED_VERSION_KEY = "happyHourSeedVersion";
// Hand-bumped base; venues.json carries a content-derived data_version that
// is appended at load time, so every pipeline re-sync reseeds cached clients.
const SEED_VERSION_BASE = "2026-vancouver-json-v1";
const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

// ---------- Venue accessors ----------
// Venue records mirror the Google Places API response shape (see
// venues-data.js). These accessors are the one place that knows how to
// read that shape, so a future real Places API sync only has to keep
// this file's contract, not every call site.

function getAddress(venue) {
  return venue.formatted_address || "";
}
function getPhone(venue) {
  return venue.formatted_phone_number || "";
}
function getLat(venue) {
  return venue.geometry?.location?.lat;
}
function getLng(venue) {
  return venue.geometry?.location?.lng;
}
function getDays(venue) {
  return venue.happy_hour.days;
}
function getStart(venue) {
  return venue.happy_hour.start;
}
function getEnd(venue) {
  return venue.happy_hour.end;
}
function getDeals(venue) {
  return venue.happy_hour.deals || [];
}

// Amenity checks used by the filter panel. outdoor_seating/gluten_free_options
// read straight off amenities; has_food/has_drink/near_transit/parking are
// computed (from deals categories, transit.walkable, and "any parking key
// is true") rather than being amenity fields themselves.
function hasAmenity(venue, key) {
  const amenities = venue.amenities || {};
  switch (key) {
    case "outdoor_seating":
      return amenities.outdoor_seating === true;
    case "gluten_free_options":
      return amenities.gluten_free_options === true;
    case "has_food":
      return getDeals(venue).some((d) => (d.category || "food") === "food");
    case "has_drink":
      return getDeals(venue).some((d) => (d.category || "food") === "drink");
    case "near_transit":
      return amenities.transit?.walkable === true;
    case "parking":
      return !!amenities.parking && Object.values(amenities.parking).some(Boolean);
    case "late_night":
      // Any advertised window starting 8pm or later (primary or extra).
      return venueWindows(venue).some((w) => w.start >= "20:00");
    default:
      return false;
  }
}

let venues = loadCachedVenues();
loadVenueData();
let currentFilter = "all";
let currentView = "list";
let searchQuery = "";
let activeAmenityFilters = new Set();
let selectedDays = new Set();
let editingId = null;
let map = null;
let mapMarkers = new Map(); // venue id -> Leaflet marker
// Carousel<->map sync state. Only HUMAN input may pan the map: a real
// touch/wheel on the carousel arms the observer's settle-pan, and any
// programmatic scroll (pin taps) disarms it. Timer-based suppression broke
// on iOS, where momentum and snap corrections deliver observer events well
// after a programmatic scroll "finished".
let carouselUserActive = false;
let carouselSettleTimer = null;
let carouselPendingId = null;
let mapCardObserver = null;
// "You are here" layers live outside mapMarkers so renderMap's venue-pin
// teardown never removes them.
let userLocDot = null;
let userLocHalo = null;
let mapToastTimer = null;

const els = {
  venueList: document.getElementById("venueList"),
  listView: document.getElementById("listView"),
  mapView: document.getElementById("mapView"),
  mapEmpty: document.getElementById("mapEmpty"),
  mapBackToListBtn: document.getElementById("mapBackToListBtn"),
  mapLocateBtn: document.getElementById("mapLocateBtn"),
  mapToast: document.getElementById("mapToast"),
  modal: document.getElementById("venueModal"),
  modalTitle: document.getElementById("modalTitle"),
  form: document.getElementById("venueForm"),
  venueId: document.getElementById("venueId"),
  venueName: document.getElementById("venueName"),
  venueAddress: document.getElementById("venueAddress"),
  venuePhone: document.getElementById("venuePhone"),
  dayPicker: document.getElementById("dayPicker"),
  startTime: document.getElementById("startTime"),
  endTime: document.getElementById("endTime"),
  dealsList: document.getElementById("dealsList"),
  deleteBtn: document.getElementById("deleteVenueBtn"),
  searchInput: document.getElementById("searchInput"),
  filterBtn: document.getElementById("filterBtn"),
  filterCount: document.getElementById("filterCount"),
  filterModal: document.getElementById("filterModal"),
  mapCardCarousel: document.getElementById("mapCardCarousel"),
};

// Instant paint from the localStorage cache (whatever version), then
// loadVenueData() fetches venues.json and reseeds when the data changed.
function loadCachedVenues() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw);
  } catch {
    // ignore — fetch will populate
  }
  return [];
}

// Fetch the merged dataset (generated by pipeline/writeback.js). no-cache
// makes the browser revalidate with the CDN (ETag), so updates land without
// hand-bumped query strings while repeat loads stay a cheap 304.
async function loadVenueData() {
  try {
    const res = await fetch("venues.json", { cache: "no-cache" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const { data_version, venues: fresh } = await res.json();
    const version = `${SEED_VERSION_BASE}:${data_version}`;
    if (localStorage.getItem(SEED_VERSION_KEY) !== version || venues.length === 0) {
      venues = fresh;
      try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(venues));
        localStorage.setItem(SEED_VERSION_KEY, version);
      } catch {
        // storage full/blocked — the in-memory copy still works this session
      }
      render();
    }
  } catch {
    // offline or fetch failed — keep whatever the cache gave us
  }
}

function newManualVenue() {
  return {
    id: crypto.randomUUID(),
    place_id: null,
    name: "",
    formatted_address: "",
    address_components: null,
    geometry: null,
    formatted_phone_number: "",
    international_phone_number: null,
    website: null,
    types: [],
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [],
    happy_hour: { days: [1, 2, 3, 4, 5], start: "16:00", end: "18:00", deals: [] },
    data_source: "manual",
    last_synced_at: null,
  };
}

function saveVenues() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(venues));
}

function pad(n) {
  return String(n).padStart(2, "0");
}

function setTimeOnDate(date, hhmm) {
  const [h, m] = hhmm.split(":").map(Number);
  const d = new Date(date);
  d.setHours(h, m, 0, 0);
  return d;
}

function addDays(date, n) {
  const d = new Date(date);
  d.setDate(d.getDate() + n);
  return d;
}

// All of a venue's recurring windows: the primary plus any extra_windows
// (late-night etc.). A null end means "until close" — treated as 23:59.
function venueWindows(venue) {
  const hh = venue.happy_hour;
  const windows = [{ days: hh.days, start: hh.start, end: hh.end }];
  for (const w of hh.extra_windows || []) {
    if (w?.days?.length && w.start) windows.push({ days: w.days, start: w.start, end: w.end || "23:59" });
  }
  return windows;
}

// Returns { status: 'live'|'upcoming'|'none', start, end } for a venue relative
// to now, considering every window it advertises.
function getVenueOccurrence(venue, now) {
  let bestUpcoming = null;
  let activeOccurrence = null;
  const windows = venueWindows(venue);

  for (let offset = -1; offset <= 7; offset++) {
    const day = addDays(now, offset);
    const dow = day.getDay();
    for (const win of windows) {
      if (!win.days.includes(dow)) continue;

      let start = setTimeOnDate(day, win.start);
      let end = setTimeOnDate(day, win.end);
      if (end <= start) end = addDays(end, 1); // overnight happy hour

      if (now >= start && now < end) {
        if (!activeOccurrence || end > activeOccurrence.end) activeOccurrence = { start, end };
      } else if (start > now) {
        if (!bestUpcoming || start < bestUpcoming.start) {
          bestUpcoming = { start, end };
        }
      }
    }
  }

  if (activeOccurrence) return { status: "live", ...activeOccurrence };
  if (bestUpcoming) return { status: "upcoming", ...bestUpcoming };
  return { status: "none" };
}

function compressDays(days) {
  if (days.length === 7) return "Daily";
  const sorted = [...days].sort((a, b) => a - b);
  const runs = [];
  let run = [sorted[0]];
  for (let i = 1; i < sorted.length; i++) {
    if (sorted[i] === run[run.length - 1] + 1) {
      run.push(sorted[i]);
    } else {
      runs.push(run);
      run = [sorted[i]];
    }
  }
  runs.push(run);

  return runs
    .map((r) =>
      r.length >= 3 ? `${DAY_NAMES[r[0]]}–${DAY_NAMES[r[r.length - 1]]}` : r.map((d) => DAY_NAMES[d]).join(", ")
    )
    .join(", ");
}

function scheduleText(venue) {
  const dayLabels = compressDays(getDays(venue));
  const startLabel = new Date(`1970-01-01T${getStart(venue)}`).toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });
  const endLabel = new Date(`1970-01-01T${getEnd(venue)}`).toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });
  return `${dayLabels} · ${startLabel}–${endLabel}`;
}

function getOccurrences() {
  const now = new Date();
  return venues.map((v) => ({ venue: v, occ: getVenueOccurrence(v, now) }));
}

// Re-render on real state changes only (filter/search/venue edits). A live
// happy-hour's status can still flip between renders, so a coarse interval
// below catches that — but nothing redraws every second anymore, since that
// was tearing down and rebuilding the horizontal card rows mid-scroll.
function render() {
  const occurrences = getOccurrences();
  renderList(occurrences, new Date());
}

// Runs only when venues/filter/view actually change — rebuilding Leaflet
// markers every second would close open popups and reset the viewport.
function renderMapView() {
  if (currentView === "map") renderMap(getOccurrences());
}

function applyFilters(occurrences) {
  let filtered = occurrences;

  if (currentFilter === "active") {
    filtered = filtered.filter((o) => o.occ.status === "live");
  } else if (currentFilter === "upcoming") {
    filtered = filtered.filter((o) => o.occ.status === "upcoming");
  }

  const query = searchQuery.trim().toLowerCase();
  if (query) {
    filtered = filtered.filter(
      (o) =>
        o.venue.name.toLowerCase().includes(query) ||
        getAddress(o.venue).toLowerCase().includes(query) ||
        getDeals(o.venue).some((d) => d.name.toLowerCase().includes(query))
    );
  }

  for (const key of activeAmenityFilters) {
    filtered = filtered.filter((o) => hasAmenity(o.venue, key));
  }

  return filtered;
}

// Groups cards by the hour their happy hour starts (per the "Weekly View"
// reference: https://figma.com/design/.../?node-id=1708-35683) — e.g. a
// 2:00pm and a 2:30pm start both land in the "Starts at 2pm" bucket, while
// the exact range still shows on each card's own pill.
function startHourBucket(venue) {
  const [h] = getStart(venue).split(":").map(Number);
  const label = new Date(`1970-01-01T${pad(h)}:00`).toLocaleTimeString([], { hour: "numeric" });
  return { key: h, label: `Starts at ${label.replace(" ", "").toLowerCase()}` };
}

function shortAddress(venue) {
  const c = venue.address_components;
  if (c?.route) return c.street_number ? `${c.street_number} ${c.route}` : c.route;
  return getAddress(venue).split(",")[0] || "";
}

function renderList(occurrences, now) {
  let filtered = applyFilters(occurrences);

  filtered = [...filtered].sort((a, b) => {
    const rank = { live: 0, upcoming: 1, none: 2 };
    const r = rank[a.occ.status] - rank[b.occ.status];
    if (r !== 0) return r;
    const at = a.occ.start ? a.occ.start.getTime() : Infinity;
    const bt = b.occ.start ? b.occ.start.getTime() : Infinity;
    return at - bt;
  });

  els.venueList.innerHTML = "";

  if (filtered.length === 0) {
    const empty = document.createElement("div");
    empty.className = "empty-state";
    empty.textContent =
      venues.length === 0
        ? "No spots yet. Tap “+ Add Spot” to add your first happy hour."
        : "Nothing matches this filter.";
    els.venueList.appendChild(empty);
    return;
  }

  const groups = new Map();
  for (const item of filtered) {
    const bucket = startHourBucket(item.venue);
    if (!groups.has(bucket.key)) groups.set(bucket.key, { label: bucket.label, items: [] });
    groups.get(bucket.key).items.push(item);
  }

  for (const key of [...groups.keys()].sort((a, b) => a - b)) {
    const { label, items } = groups.get(key);

    const group = document.createElement("div");
    group.className = "time-group";

    const heading = document.createElement("p");
    heading.className = "time-group-label";
    heading.textContent = label;
    group.appendChild(heading);

    const row = document.createElement("div");
    row.className = "time-group-row";
    for (const { venue, occ } of items) {
      row.appendChild(renderWeeklyCard(venue, occ, now));
    }
    group.appendChild(row);

    els.venueList.appendChild(group);
  }
}

function renderWeeklyCard(venue, occ, now) {
  const card = document.createElement("div");
  card.className = "weekly-card";
  card.addEventListener("click", () => {
    window.location.href = `menu.html?id=${encodeURIComponent(venue.id)}`;
  });

  const photo = document.createElement("div");
  photo.className = "weekly-card-photo";
  if (venue.cover_image?.url) {
    photo.style.backgroundImage = `url("${venue.cover_image.url}")`;
  } else {
    photo.classList.add("placeholder");
    photo.textContent = "🍸";
  }

  const pill = document.createElement("span");
  pill.className = `weekly-card-pill ${occ.status === "live" ? "live" : ""}`;
  pill.textContent = `${formatShortTime(getStart(venue))}–${formatShortTime(getEnd(venue))}`;
  photo.appendChild(pill);

  const editBtn = document.createElement("button");
  editBtn.type = "button";
  editBtn.className = "weekly-card-edit";
  editBtn.setAttribute("aria-label", "Edit spot");
  editBtn.textContent = "✎";
  editBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    openModal(venue);
  });
  photo.appendChild(editBtn);

  card.appendChild(photo);

  const name = document.createElement("p");
  name.className = "weekly-card-name";
  name.textContent = venue.name;
  card.appendChild(name);

  const meta = document.createElement("p");
  meta.className = "weekly-card-meta";
  meta.textContent = shortAddress(venue);
  card.appendChild(meta);

  return card;
}

function formatShortTime(hhmm) {
  const [h, m] = hhmm.split(":").map(Number);
  const period = h >= 12 ? "pm" : "am";
  const hour12 = h % 12 === 0 ? 12 : h % 12;
  const time = m === 0 ? `${hour12}` : `${hour12}:${pad(m)}`;
  return `${time}${period}`;
}

// ---------- Map view ----------

// MAPBOX_TOKEN comes from config.js, which is generated at deploy time
// from a GitHub Actions secret and is NOT committed to the repo — see
// config.example.js and .github/workflows/deploy.yml.
// Light style: the dark tiles buried the pins and read poorly against the
// app's white/amber design.
const MAPBOX_STYLE = "light-v11";

function ensureMap() {
  if (map) return map;
  map = L.map("map", { attributionControl: true }).setView([49.2698, -123.1207], 13);
  L.tileLayer(
    `https://api.mapbox.com/styles/v1/mapbox/${MAPBOX_STYLE}/tiles/{z}/{x}/{y}{r}?access_token=${MAPBOX_TOKEN}`,
    {
      maxZoom: 19,
      tileSize: 512,
      zoomOffset: -1,
      attribution:
        '&copy; <a href="https://www.mapbox.com/about/maps/">Mapbox</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    }
  ).addTo(map);

  // Double-tap to zoom. Leaflet 1.8+ relies on native dblclick, which mobile
  // Safari withholds (it reserves double-tap for page smart-zoom) — so detect
  // the double tap ourselves and zoom around the tapped point. Marker taps
  // are excluded; preventDefault stops the browser's own smart-zoom.
  const container = map.getContainer();
  let lastTap = null;
  container.addEventListener("touchend", (e) => {
    if (e.touches.length || e.changedTouches.length !== 1) { lastTap = null; return; }
    if (e.target.closest(".map-pin")) { lastTap = null; return; }
    const t = e.changedTouches[0];
    const now = Date.now();
    if (lastTap && now - lastTap.time < 300 && Math.hypot(t.clientX - lastTap.x, t.clientY - lastTap.y) < 40) {
      lastTap = null;
      e.preventDefault();
      const rect = container.getBoundingClientRect();
      map.setZoomAround(L.point(t.clientX - rect.left, t.clientY - rect.top), map.getZoom() + 1);
    } else {
      lastTap = { time: now, x: t.clientX, y: t.clientY };
    }
  }, { passive: false });

  return map;
}

function showMapToast(msg) {
  els.mapToast.textContent = msg;
  els.mapToast.classList.remove("hidden");
  clearTimeout(mapToastTimer);
  mapToastTimer = setTimeout(() => els.mapToast.classList.add("hidden"), 2600);
}

function locateMe() {
  if (!navigator.geolocation) {
    showMapToast("Location isn't supported on this device");
    return;
  }
  const btn = els.mapLocateBtn;
  btn.classList.add("locating");
  navigator.geolocation.getCurrentPosition(
    (pos) => {
      btn.classList.remove("locating");
      btn.classList.add("located");
      const m = ensureMap();
      const ll = [pos.coords.latitude, pos.coords.longitude];
      if (!userLocDot) {
        userLocDot = L.marker(ll, {
          icon: L.divIcon({ className: "user-loc-dot", html: "<span></span>", iconSize: [22, 22], iconAnchor: [11, 11] }),
          zIndexOffset: 9500,
          interactive: false,
        }).addTo(m);
        userLocHalo = L.circle(ll, {
          radius: pos.coords.accuracy || 50,
          color: "#2f7cf6",
          weight: 1,
          opacity: 0.35,
          fillColor: "#2f7cf6",
          fillOpacity: 0.12,
          interactive: false,
        }).addTo(m);
      } else {
        userLocDot.setLatLng(ll);
        userLocHalo.setLatLng(ll).setRadius(pos.coords.accuracy || 50);
      }
      m.flyTo(ll, Math.max(m.getZoom(), 15), { duration: 0.6 });
    },
    () => {
      btn.classList.remove("locating");
      showMapToast("Couldn't get your location — check location permissions");
    },
    { enableHighAccuracy: true, timeout: 10000, maximumAge: 30000 }
  );
}

els.mapLocateBtn.addEventListener("click", locateMe);

function markerColor(status) {
  if (status === "live") return "#34d399";
  if (status === "upcoming") return "#ff9f43";
  return "#9a9aa5";
}

function renderMap(occurrences) {
  if (currentView !== "map") return;
  const m = ensureMap();

  if (mapCardObserver) mapCardObserver.disconnect();
  mapMarkers.forEach((marker) => marker.remove());
  mapMarkers = new Map();
  els.mapCardCarousel.innerHTML = "";

  const located = applyFilters(occurrences).filter(
    (o) => typeof getLat(o.venue) === "number" && typeof getLng(o.venue) === "number"
  );

  for (const { venue, occ } of located) {
    const color = markerColor(occ.status);
    // Popularity (Google review volume) sets pin size and stacking, so the
    // busiest spots read at a glance: big starred pins on top, quiet spots
    // small and underneath. Status keeps the color channel.
    const reviews = venue.user_ratings_total || 0;
    const tier = reviews >= 2000 ? "hot" : reviews >= 500 ? "mid" : "base";
    const px = tier === "hot" ? 26 : tier === "mid" ? 20 : 15;
    const icon = L.divIcon({
      className: `map-pin map-pin-${tier}`,
      html: `<span style="background:${color}">${tier === "hot" ? "★" : ""}</span>`,
      iconSize: [px, px],
      iconAnchor: [px / 2, px / 2],
    });
    const marker = L.marker([getLat(venue), getLng(venue)], { icon, zIndexOffset: Math.min(reviews, 9000) }).addTo(m);
    marker.on("click", () => selectVenue(venue.id, { pan: true, scrollCarousel: true }));
    mapMarkers.set(venue.id, marker);

    els.mapCardCarousel.appendChild(buildMapCard(venue, occ));
  }

  els.mapEmpty.classList.toggle("hidden", located.length > 0);
  els.mapCardCarousel.classList.toggle("hidden", located.length === 0);

  // Keep the locate button just above the carousel, whose height depends on
  // card content.
  const carouselHeight = located.length === 0 ? 0 : els.mapCardCarousel.getBoundingClientRect().height;
  els.mapLocateBtn.style.bottom = `${carouselHeight + 14}px`;

  // Swiping a card into view highlights its pin instantly (cheap), but the
  // map pans only once, ~160ms after the LAST card change — and only when
  // the swipe came from the user (carouselUserActive). Programmatic scrolls
  // can highlight but never move the map.
  mapCardObserver = new IntersectionObserver(
    (entries) => {
      const visible = entries.find((e) => e.isIntersecting && e.intersectionRatio >= 0.6);
      if (!visible) return;
      highlightPin(visible.target.dataset.venueId);
      if (!carouselUserActive) return;
      carouselPendingId = visible.target.dataset.venueId;
      clearTimeout(carouselSettleTimer);
      carouselSettleTimer = setTimeout(() => panToVenue(carouselPendingId), 160);
    },
    { root: els.mapCardCarousel, threshold: 0.6 }
  );
  els.mapCardCarousel.querySelectorAll(".map-detail-card").forEach((card) => mapCardObserver.observe(card));

  // invalidateSize() must run before fitBounds() — the map view is now
  // position:fixed/full-viewport, so the container's true size (and thus
  // which tiles Leaflet loads) is only correct after that recalculation.
  // Fitting bounds first left it centered on stale, mostly-blank tiles.
  setTimeout(() => {
    m.invalidateSize();
    if (located.length > 0) {
      const bounds = L.latLngBounds(located.map((o) => [getLat(o.venue), getLng(o.venue)]));
      m.fitBounds(bounds, { padding: [30, 30], maxZoom: 15 });
    }
  }, 0);
}

function buildMapCard(venue, occ) {
  const card = document.createElement("div");
  card.className = "map-detail-card";
  card.dataset.venueId = venue.id;
  card.addEventListener("click", () => {
    window.location.href = `menu.html?id=${encodeURIComponent(venue.id)}`;
  });

  const body = document.createElement("div");
  body.className = "map-detail-body";
  card.appendChild(body);

  const name = document.createElement("h3");
  name.className = "map-detail-name";
  name.textContent = venue.name;
  body.appendChild(name);

  const meta = document.createElement("div");
  meta.className = "map-detail-meta";
  const status = document.createElement("span");
  status.className = "map-detail-status";
  if (occ.status === "live") {
    status.classList.add("live");
    status.textContent = "Live now";
  } else if (occ.status === "upcoming") {
    status.classList.add("upcoming");
    status.textContent = "Upcoming";
  } else {
    status.textContent = "No date";
  }
  meta.appendChild(status);
  const time = document.createElement("span");
  time.className = "map-detail-time";
  time.textContent =
    occ.status === "none" ? "" : `${formatShortTime(getStart(venue))}–${formatShortTime(getEnd(venue))}`;
  meta.appendChild(time);
  if (venue.rating) {
    const rating = document.createElement("span");
    rating.className = "map-detail-rating";
    rating.textContent = `★ ${venue.rating}`;
    meta.appendChild(rating);
  }
  body.appendChild(meta);

  const address = getAddress(venue);
  if (address) {
    const addressEl = document.createElement("div");
    addressEl.className = "map-detail-address";
    addressEl.textContent = address;
    body.appendChild(addressEl);
  }

  const actions = document.createElement("div");
  actions.className = "map-detail-actions";
  body.appendChild(actions);

  if (address) {
    const directions = document.createElement("a");
    directions.className = "map-detail-action";
    directions.target = "_blank";
    directions.rel = "noopener";
    directions.href = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;
    directions.addEventListener("click", (e) => e.stopPropagation());
    directions.innerHTML = `<span class="map-detail-action-icon">🧭</span><span>Get directions</span>`;
    actions.appendChild(directions);
  }

  const menuUrl = `menu.html?id=${encodeURIComponent(venue.id)}`;
  const viewMenu = document.createElement("a");
  viewMenu.className = "map-detail-action";
  viewMenu.href = menuUrl;
  viewMenu.innerHTML = `<span class="map-detail-action-icon">📋</span><span>View menu</span>`;
  actions.appendChild(viewMenu);

  const arrow = document.createElement("a");
  arrow.className = "map-detail-arrow-btn";
  arrow.href = menuUrl;
  arrow.setAttribute("aria-label", "View menu");
  arrow.textContent = "→";
  arrow.addEventListener("click", (e) => e.stopPropagation());
  card.appendChild(arrow);

  return card;
}

function highlightPin(venueId) {
  mapMarkers.forEach((mk, id) => {
    mk.getElement()?.classList.toggle("map-pin-active", id === venueId);
  });
}

function panToVenue(venueId) {
  const marker = mapMarkers.get(venueId);
  if (!marker || !map) return;
  // Already near center? Skip the pan — micro-adjustments read as jitter.
  const point = map.latLngToContainerPoint(marker.getLatLng());
  const size = map.getSize();
  if (Math.abs(point.x - size.x / 2) < size.x / 5 && Math.abs(point.y - size.y / 2) < size.y / 5) return;
  map.panTo(marker.getLatLng(), { animate: true, duration: 0.5, easeLinearity: 0.3 });
}

function selectVenue(venueId, { pan = false, scrollCarousel = false } = {}) {
  if (!mapMarkers.has(venueId)) return;
  highlightPin(venueId);
  clearTimeout(carouselSettleTimer); // a direct selection outranks a settling swipe
  if (pan) panToVenue(venueId);

  if (scrollCarousel) {
    const card = els.mapCardCarousel.querySelector(`[data-venue-id="${CSS.escape(venueId)}"]`);
    if (card) {
      // Programmatic scroll: disarm the observer's pan. Late observer events
      // (iOS momentum, snap corrections) can highlight but never move the map
      // until the user touches the carousel again.
      carouselUserActive = false;
      card.scrollIntoView({ behavior: "smooth", inline: "center", block: "nearest" });
    }
  }
}

// Real user input on the carousel re-arms the observer's settle-pan.
for (const evt of ["touchstart", "wheel", "pointerdown"]) {
  els.mapCardCarousel.addEventListener(evt, () => { carouselUserActive = true; }, { passive: true });
}

// ---------- Modal handling ----------

function openModal(venue) {
  editingId = venue ? venue.id : null;
  els.modalTitle.textContent = venue ? "Edit Spot" : "Add a Spot";
  els.deleteBtn.classList.toggle("hidden", !venue);

  els.venueId.value = venue ? venue.id : "";
  els.venueName.value = venue ? venue.name : "";
  els.venueAddress.value = venue ? getAddress(venue) : "";
  els.venuePhone.value = venue ? getPhone(venue) : "";
  els.startTime.value = venue ? getStart(venue) : "16:00";
  els.endTime.value = venue ? getEnd(venue) : "18:00";

  selectedDays = new Set(venue ? getDays(venue) : [1, 2, 3, 4, 5]);
  renderDayPicker();

  els.dealsList.innerHTML = "";
  const deals = venue && getDeals(venue).length ? getDeals(venue) : [{ name: "", price: "", category: "food", description: "" }];
  for (const d of deals) addDealRow(d.name, d.price, d.category, d.description);

  els.modal.classList.remove("hidden");
}

function closeModal() {
  els.modal.classList.add("hidden");
  editingId = null;
}

function renderDayPicker() {
  els.dayPicker.querySelectorAll(".day-btn").forEach((btn) => {
    const day = Number(btn.dataset.day);
    btn.classList.toggle("selected", selectedDays.has(day));
  });
}

els.dayPicker.addEventListener("click", (e) => {
  const btn = e.target.closest(".day-btn");
  if (!btn) return;
  const day = Number(btn.dataset.day);
  if (selectedDays.has(day)) selectedDays.delete(day);
  else selectedDays.add(day);
  renderDayPicker();
});

function addDealRow(name = "", price = "", category = "food", description = "") {
  const row = document.createElement("div");
  row.className = "deal-edit-row";
  row.innerHTML = `
    <div class="deal-edit-row-main">
      <input type="text" class="deal-name" placeholder="Deal (e.g. Draft beers)" value="${escapeHtml(name)}" />
      <input type="text" class="deal-price" placeholder="Price" value="${escapeHtml(price)}" />
      <button type="button" title="Remove">&times;</button>
    </div>
    <div class="deal-edit-row-extra">
      <select class="deal-category">
        <option value="food"${category === "food" ? " selected" : ""}>Food</option>
        <option value="drink"${category === "drink" ? " selected" : ""}>Drink</option>
      </select>
      <input type="text" class="deal-description" placeholder="Description (optional)" value="${escapeHtml(description || "")}" />
    </div>
  `;
  row.querySelector("button").addEventListener("click", () => row.remove());
  els.dealsList.appendChild(row);
}

function escapeHtml(str) {
  const div = document.createElement("div");
  div.textContent = str;
  return div.innerHTML;
}

document.getElementById("closeModalBtn").addEventListener("click", closeModal);
document.getElementById("cancelBtn").addEventListener("click", closeModal);
document.getElementById("addDealBtn").addEventListener("click", () => addDealRow());

els.modal.addEventListener("click", (e) => {
  if (e.target === els.modal) closeModal();
});

els.deleteBtn.addEventListener("click", () => {
  if (!editingId) return;
  venues = venues.filter((v) => v.id !== editingId);
  saveVenues();
  closeModal();
  render();
  renderMapView();
});

els.form.addEventListener("submit", (e) => {
  e.preventDefault();

  const name = els.venueName.value.trim();
  if (!name) return;
  if (selectedDays.size === 0) {
    alert("Pick at least one day.");
    return;
  }

  const deals = [...els.dealsList.querySelectorAll(".deal-edit-row")]
    .map((row) => ({
      name: row.querySelector(".deal-name").value.trim(),
      price: row.querySelector(".deal-price").value.trim(),
      category: row.querySelector(".deal-category").value,
      description: row.querySelector(".deal-description").value.trim(),
    }))
    .filter((d) => d.name);

  // Start from the existing Places-schema record (preserving place_id,
  // geometry, rating, photos, etc. — none of which this simple form edits)
  // and only overlay the fields the form actually owns. Editing the
  // address here does NOT re-geocode it; that would need a real Places
  // API/geocoder call, which isn't wired up yet.
  const existing = editingId ? venues.find((v) => v.id === editingId) : null;
  const venueData = existing ? JSON.parse(JSON.stringify(existing)) : newManualVenue();

  venueData.id = editingId || venueData.id;
  venueData.name = name;
  venueData.formatted_address = els.venueAddress.value.trim();
  venueData.formatted_phone_number = els.venuePhone.value.trim();
  venueData.happy_hour = {
    days: [...selectedDays].sort(),
    start: els.startTime.value,
    end: els.endTime.value,
    deals,
  };

  if (editingId) {
    venues = venues.map((v) => (v.id === editingId ? venueData : v));
  } else {
    venues.push(venueData);
  }

  saveVenues();
  closeModal();
  render();
  renderMapView();
});

// Two filter-chip bars exist in the DOM (list view + the floating one over
// the map) and must stay in sync — toggle by matching data-filter rather
// than the single clicked node, so whichever bar the user last touched wins
// everywhere.
document.querySelectorAll(".filter-btn").forEach((btn) => {
  btn.addEventListener("click", () => {
    currentFilter = btn.dataset.filter;
    document.querySelectorAll(".filter-btn").forEach((b) => b.classList.toggle("active", b.dataset.filter === currentFilter));
    render();
    renderMapView();
  });
});

function setView(view) {
  currentView = view;
  document.querySelectorAll(".view-tab").forEach((b) => b.classList.toggle("active", b.dataset.view === view));
  els.listView.classList.toggle("hidden", view !== "list");
  els.mapView.classList.toggle("hidden", view !== "map");
  document.body.classList.toggle("map-fullscreen", view === "map");
  render();
  renderMapView();
}

document.querySelectorAll(".view-tab").forEach((btn) => {
  btn.addEventListener("click", () => setView(btn.dataset.view));
});

els.mapBackToListBtn.addEventListener("click", () => setView("list"));

// ---------- Search + filters ----------

els.searchInput.addEventListener("input", () => {
  searchQuery = els.searchInput.value;
  render();
  renderMapView();
});

function updateFilterButton() {
  const count = activeAmenityFilters.size;
  els.filterBtn.classList.toggle("has-active", count > 0);
  els.filterCount.classList.toggle("hidden", count === 0);
  els.filterCount.textContent = String(count);
}

function renderFilterToggles() {
  document.querySelectorAll(".filter-toggle-row").forEach((row) => {
    row.classList.toggle("active", activeAmenityFilters.has(row.dataset.amenity));
  });
}

els.filterBtn.addEventListener("click", () => {
  renderFilterToggles();
  els.filterModal.classList.remove("hidden");
});

document.getElementById("closeFilterModalBtn").addEventListener("click", () => {
  els.filterModal.classList.add("hidden");
});
document.getElementById("doneFiltersBtn").addEventListener("click", () => {
  els.filterModal.classList.add("hidden");
});
els.filterModal.addEventListener("click", (e) => {
  if (e.target === els.filterModal) els.filterModal.classList.add("hidden");
});

document.querySelectorAll(".filter-toggle-row").forEach((row) => {
  row.addEventListener("click", () => {
    const key = row.dataset.amenity;
    if (activeAmenityFilters.has(key)) activeAmenityFilters.delete(key);
    else activeAmenityFilters.add(key);
    row.classList.toggle("active");
    updateFilterButton();
    render();
    renderMapView();
  });
});

document.getElementById("clearFiltersBtn").addEventListener("click", () => {
  activeAmenityFilters.clear();
  renderFilterToggles();
  updateFilterButton();
  render();
  renderMapView();
});

render();
renderMapView();
// Coarse refresh so a card's live/upcoming status catches up to the clock —
// no need for per-second precision now that the countdown display is gone,
// and a rare interval far outruns the odds of landing mid-scroll.
setInterval(render, 60000);

// The hero is position:fixed (pinned behind the sheet so the sheet scrolls
// up to cover it) and so no longer reserves flow space on its own — measure
// its real height and feed it to the --hero-height var the sheet's
// margin-top depends on. Re-measure on resize since the title's clamp()
// sizing shifts the hero's height as viewport width changes.
const heroEl = document.querySelector(".hero");
function updateHeroHeight() {
  document.documentElement.style.setProperty("--hero-height", `${heroEl.offsetHeight}px`);
}
updateHeroHeight();
window.addEventListener("resize", updateHeroHeight);
