/**
 * Venue "database" for the Happy Hour app.
 *
 * Field names deliberately mirror the Google Places API (Place Details)
 * response shape 1:1 — place_id, formatted_address, geometry.location,
 * formatted_phone_number, opening_hours, price_level, rating, types,
 * business_status, photos — so that filling these records from a real
 * Places API call later is a direct field assignment, not a rewrite.
 *
 * IMPORTANT: scraping Google Maps pages directly violates Google's Terms
 * of Service. The supported path to populate the Google-sourced fields
 * below is the official Places API (Place Search + Place Details), which
 * has a free monthly usage credit. Until that sync exists, every
 * Google-owned field below is either null or a best-effort placeholder —
 * see `data_source` / `last_synced_at` on each record.
 *
 * `happy_hour` is our own extension — Google has no concept of it — and
 * is the only block a real Places sync should never overwrite.
 *
 * `cover_image` is also our own extension, not a Places field: a photo
 * pulled from the venue's own official website (never scraped from
 * Google/Yelp — see their respective ToS), used for display until a real
 * Places `photos` sync exists. `website` values were verified by hand
 * against each restaurant's real site, independent of any Places sync.
 */

const PLACE_TYPES_RESTAURANT_BAR = ["restaurant", "bar", "food", "point_of_interest", "establishment"];

const VENUES_SEED = [
  {
    id: "ancora",
    place_id: null,
    name: "Ancora",
    formatted_address: "1600 Howe St, Vancouver, BC",
    address_components: {
      street_number: "1600",
      route: "Howe St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2738039, lng: -123.1326024 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://www.ancoradining.com/falsecreek",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [],
    cover_image: {
      url: "https://static.wixstatic.com/media/fe927f_e8401739db154961a768366f355e2d5d.jpg",
      credit_name: "Ancora Waterfront Dining and Patio",
      credit_url: "https://www.ancoradining.com/falsecreek",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "14:30",
      end: "17:00",
      verified: true,
      verified_source: "https://www.ancoradining.com/contact",
      deals: [
        { name: "Granville Island beer", price: "$8", category: "drink", description: "16oz." },
        { name: "Cocktails", price: "$11–19", category: "drink", description: "" },
        { name: "Wine", price: "$10", category: "drink", description: "" },
        { name: "Oysters", price: "$3 ea", category: "food", description: "" },
        { name: "Brussels sprouts", price: "$8", category: "food", description: "" },
        { name: "Sashimi", price: "$16", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 800,
        walkable: false
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "earls-test-kitchen",
    place_id: null,
    name: "Earls Test Kitchen",
    formatted_address: "905 Hornby St, Vancouver, BC",
    address_components: {
      street_number: "905",
      route: "Hornby St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2815936, lng: -123.123754 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://earls.ca/locations/test-kitchen/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [],
    cover_image: {
      url: "https://earls.ca/wp-content/uploads/2025/03/edit_testkitchen_0144.jpg__2000x0_q80_crop-smart_subsampling-2_upscale.jpg",
      credit_name: "Earls Test Kitchen",
      credit_url: "https://earls.ca/locations/test-kitchen/",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "15:00",
      end: "18:00",
      verified: true,
      verified_source: "https://earls.ca/locations/test-kitchen/menu/happy-hour/",
      deals: [
        { name: "Select beers", price: "$3 off", category: "drink", description: "" },
        { name: "Wine, cocktails, margarita, spritz", price: "50% off", category: "drink", description: "" },
        { name: "Oysters", price: "$3.50 ea", category: "food", description: "" },
        { name: "Fries", price: "$5", category: "food", description: "" },
        { name: "Tacos", price: "$7", category: "food", description: "" },
        { name: "Pizza", price: "$15", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Vancouver City Centre",
        distance_m: 380,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "homer-st-cafe-and-bar",
    place_id: null,
    name: "Homer St. Cafe and Bar",
    formatted_address: "898 Homer St, Vancouver, BC",
    address_components: {
      street_number: "898",
      route: "Homer St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2784178, lng: -123.118217 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://www.homerstreetcafebar.com/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [
      {
        url: "https://static.wixstatic.com/media/fc95b3_bd8f4b64f6f147adb3e101cb8c08d604~mv2.jpg/v1/fill/w_613,h_460,fp_0.45_0.63,q_90,enc_avif,quality_auto/fc95b3_bd8f4b64f6f147adb3e101cb8c08d604~mv2.jpg",
        credit_name: "Homer St. Cafe and Bar",
        credit_url: "https://www.homerstreetcafebar.com/",
        source: "official_website",
      },
      {
        url: "https://static.wixstatic.com/media/fc95b3_9aeb8b3113b449fba5f90dffe439ced9~mv2.jpg/v1/fill/w_613,h_460,q_90,enc_avif,quality_auto/fc95b3_9aeb8b3113b449fba5f90dffe439ced9~mv2.jpg",
        credit_name: "Homer St. Cafe and Bar",
        credit_url: "https://www.homerstreetcafebar.com/",
        source: "official_website",
      },
    ],
    cover_image: {
      url: "https://static.wixstatic.com/media/fc95b3_a90972eda53b4d9785a37282f5584515~mv2.jpeg",
      credit_name: "Homer St. Cafe and Bar",
      credit_url: "https://www.homerstreetcafebar.com/",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "14:30",
      end: "17:30",
      deals: [
        { name: "Beer", price: "$5–8", category: "drink", description: "" },
        { name: "Wine", price: "$7", category: "drink", description: "By the glass." },
        { name: "Highballs", price: "$5", category: "drink", description: "" },
        { name: "House-made puff pastry", price: "$6", category: "food", description: "" },
        { name: "Rolls", price: "$8", category: "food", description: "" },
        { name: "Burger", price: "$22", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Granville",
        distance_m: 476,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "hapa-izakaya-yaletown",
    place_id: null,
    name: "Hapa Izakaya Yaletown",
    formatted_address: "1193 Hamilton St, Vancouver, BC",
    address_components: {
      street_number: "1193",
      route: "Hamilton St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.275171, lng: -123.122572 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://hapaizakaya.com/locations-yaletown/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [
      {
        url: "https://hapaizakaya.com/wp-content/uploads/hapa_izakaya_yaletown_bar.jpg",
        credit_name: "Hapa Izakaya Yaletown",
        credit_url: "https://hapaizakaya.com/locations-yaletown/",
        source: "official_website",
      },
      {
        url: "https://hapaizakaya.com/wp-content/uploads/hapa_izakaya_yaletown.jpg",
        credit_name: "Hapa Izakaya Yaletown",
        credit_url: "https://hapaizakaya.com/locations-yaletown/",
        source: "official_website",
      },
    ],
    cover_image: {
      url: "https://hapaizakaya.com/wp-content/uploads/hapa_izakaya_yaletown_patio.jpg",
      credit_name: "Hapa Izakaya Yaletown",
      credit_url: "https://hapaizakaya.com/locations-yaletown/",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "16:00",
      end: "18:00",
      verified: true,
      verified_source: "https://hapaizakaya.com/yaletown-menu/",
      deals: [
        { name: "Draft beer", price: "$5", category: "drink", description: "" },
        { name: "Wine", price: "$6", category: "drink", description: "" },
        { name: "Cocktails", price: "$3 off", category: "drink", description: "" },
        { name: "Edamame", price: "$8", category: "food", description: "" },
        { name: "Takoyaki", price: "$9", category: "food", description: "" },
        { name: "Rolls", price: "$10–12", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 120,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "boulevard-kitchen-oyster-bar",
    place_id: null,
    name: "Boulevard Kitchen & Oyster Bar",
    formatted_address: "845 Burrard St, Vancouver, BC",
    address_components: {
      street_number: "845",
      route: "Burrard St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2829266, lng: -123.123798 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://boulevardvancouver.ca/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [],
    cover_image: {
      url: "https://boulevardvancouver.ca/wp-content/uploads/2024/12/Best-seafood-restaurant-in-vancouver-BC-Boulevard-Kitchen-and-Oyster-Bar-e1733947768621.jpg",
      credit_name: "Boulevard Kitchen & Oyster Bar",
      credit_url: "https://boulevardvancouver.ca/",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "15:00",
      end: "17:00",
      verified: true,
      verified_source: "https://boulevardvancouver.ca/happy-hour/",
      deals: [
        { name: "Beer", price: "$7", category: "drink", description: "" },
        { name: "Wine", price: "$8", category: "drink", description: "" },
        { name: "Cocktails", price: "$10–15", category: "drink", description: "" },
        { name: "Oysters", price: "$2 ea", category: "food", description: "" },
        { name: "Marcona almonds", price: "$8", category: "food", description: "" },
        { name: "Fries", price: "$10", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Vancouver City Centre",
        distance_m: 363,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "chambar",
    place_id: null,
    name: "Chambar Belgian Restaurant",
    formatted_address: "568 Beatty St, Vancouver, BC",
    address_components: {
      street_number: "568",
      route: "Beatty St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2801513, lng: -123.109872 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://www.chambar.com/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [
      {
        url: "https://www.chambar.com/media/DINNER_LO_Mussels_Scott%20Little%20IMG_1313.jpg",
        credit_name: "Chambar Belgian Restaurant",
        credit_url: "https://www.chambar.com/",
        source: "official_website",
      },
      {
        url: "https://www.chambar.com/media/DINNER_LO_Halibut_Jlow_1H2A2525.jpg",
        credit_name: "Chambar Belgian Restaurant",
        credit_url: "https://www.chambar.com/",
        source: "official_website",
      },
    ],
    cover_image: {
      url: "https://www.chambar.com/media/740x9999/COCKTAIL_LO_BlueFig_ScottLittle_IMG_5848%20Annecdote%20Blue%20Fig.jpg",
      credit_name: "Chambar Belgian Restaurant",
      credit_url: "https://www.chambar.com/",
      source: "official_website",
    },
    happy_hour: {
      days: [1, 2, 3, 4, 5],
      start: "15:00",
      end: "16:30",
      verified: true,
      verified_source: "https://www.chambar.com/menus/happyhour/",
      deals: [
        { name: "Beer", price: "$3 off", category: "drink", description: "" },
        { name: "Cocktails", price: "$9–10", category: "drink", description: "" },
        { name: "Wine", price: "$2 off", category: "drink", description: "" },
        { name: "Focaccia", price: "$6", category: "food", description: "" },
        { name: "Frites", price: "$8", category: "food", description: "" },
        { name: "Salads", price: "$13–16", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Stadium-Chinatown",
        distance_m: 101,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "d6-bar-lounge",
    place_id: null,
    // Corrected after initial research pointed at the wrong building —
    // D/6 is the rooftop lounge atop the DOUGLAS, Autograph Collection
    // (Parq Vancouver), not Rosewood Hotel Georgia. Verified against its
    // own happy hour menu PDF.
    name: "D/6 Lounge",
    formatted_address: "39 Smithe St, Vancouver, BC",
    address_components: {
      street_number: "39",
      route: "Smithe St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2756315, lng: -123.1134717 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://www.parqcasino.com/d-6-lounge",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [
      {
        url: "https://static.wixstatic.com/media/93f176_93e9b668ed06483ea0aa7ea600e78499~mv2.jpg/v1/fill/w_241,h_363,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/DSC00622.jpg",
        credit_name: "D/6 Lounge",
        credit_url: "https://www.parqcasino.com/d-6-lounge",
        source: "official_website",
      },
      {
        url: "https://static.wixstatic.com/media/93f176_467f1b37761545eab5722a9f72709723~mv2.jpg/v1/fill/w_147,h_221,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/93f176_467f1b37761545eab5722a9f72709723~mv2.jpg",
        credit_name: "D/6 Lounge",
        credit_url: "https://www.parqcasino.com/d-6-lounge",
        source: "official_website",
      },
    ],
    cover_image: {
      url: "https://static.wixstatic.com/media/6eb957_a0b0c870489f44fd823ac376555b0126~mv2.jpg",
      credit_name: "D/6 Lounge",
      credit_url: "https://www.parqcasino.com/d-6-lounge",
      source: "official_website",
    },
    happy_hour: {
      // Menu says "Daily until 7pm | Sunday all day" — start time isn't
      // printed, so 5pm is inferred from the "After Office" 5-7pm deal.
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "17:00",
      end: "19:00",
      verified: true,
      verified_source:
        "https://www.parqcasino.com/_files/ugd/93f176_2fd639380cfc4f2f90f0f842fdfcbd8d.pdf",
      deals: [
        { name: "Wine", price: "$12", category: "drink", description: "6oz." },
        { name: "Sake", price: "$12", category: "drink", description: "5oz." },
        { name: "Beer", price: "$7", category: "drink", description: "14oz. Madri or Granville Island IPA." },
        { name: "Truffle fries", price: "$16", category: "food", description: "Triple cooked, parmigiano reggiano, truffle aioli." },
        {
          name: "Jumbo prawn cocktail",
          price: "$31",
          category: "food",
          description: "Tiger prawns, wasabi cocktail sauce. Gluten-free.",
        },
        { name: "Chicken kara-age", price: "$21", category: "food", description: "Agave citrus, red chili dip." },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: true,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Stadium-Chinatown",
        distance_m: 504,
        walkable: false
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "havana",
    place_id: null,
    name: "Havana",
    formatted_address: "1212 Commercial Dr, Vancouver, BC",
    address_components: {
      street_number: "1212",
      route: "Commercial Dr",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.273703, lng: -123.0693627 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://www.havanavancouver.com/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [
      {
        url: "https://images.squarespace-cdn.com/content/v1/5dc5cfa1f5318a3348ec2af7/1737403701670-I3UG0H7TWTKTE2QHUSUF/havana-vancouver-interior.jpeg",
        credit_name: "Havana Vancouver",
        credit_url: "https://www.havanavancouver.com/",
        source: "official_website",
      },
      {
        url: "https://images.squarespace-cdn.com/content/v1/5dc5cfa1f5318a3348ec2af7/1723504679194-0M6M717KIKHFR89H14JV/sharing-with-friends-havana-vancouver.jpg",
        credit_name: "Havana Vancouver",
        credit_url: "https://www.havanavancouver.com/",
        source: "official_website",
      },
    ],
    cover_image: {
      url: "https://images.squarespace-cdn.com/content/5dc5cfa1f5318a3348ec2af7/1737403669798-S9OBN78HPKPZY25SCABA/havana-vancouver-dining.jpeg",
      credit_name: "Havana Vancouver",
      credit_url: "https://www.havanavancouver.com/",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "15:00",
      end: "17:00",
      verified: true,
      verified_source: "https://www.havanavancouver.com/",
      deals: [
        { name: "Beer", price: "$7", category: "drink", description: "16oz." },
        { name: "Wine", price: "$7–10", category: "drink", description: "" },
        { name: "Margaritas", price: "$11", category: "drink", description: "" },
        { name: "Fries", price: "$5–7", category: "food", description: "" },
        { name: "Sandwich", price: "$12", category: "food", description: "" },
        { name: "Ceviche", price: "$16", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Commercial-Broadway",
        distance_m: 1235,
        walkable: false
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "brewhall",
    place_id: null,
    name: "Brewhall",
    formatted_address: "97 E 2nd Ave, Vancouver, BC",
    address_components: {
      street_number: "97",
      route: "E 2nd Ave",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2695303, lng: -123.1036822 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://brewhall.com/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [],
    cover_image: {
      url: "https://brewhall.com/wp-content/uploads/2026/05/KristinaLorissaPhotography-24.png",
      credit_name: "Brewhall",
      credit_url: "https://brewhall.com/",
      source: "official_website",
    },
    happy_hour: {
      days: [2, 3, 4, 5],
      start: "14:00",
      end: "18:00",
      verified: true,
      verified_source: "https://brewhall.com/",
      deals: [
        { name: "Beer", price: "$5–6.25", category: "drink", description: "" },
        { name: "Wine", price: "50% off", category: "drink", description: "" },
        { name: "Cocktails", price: "25% off", category: "drink", description: "" },
        { name: "Full food menu", price: "25% off", category: "food", description: "" },
        { name: "Burger", price: "$10", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: {
        paid_lot: true
      },
      transit: {
        nearest_station: "Main St-Science World",
        distance_m: 506,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
  {
    id: "glowbal",
    place_id: null,
    name: "Glowbal",
    formatted_address: "590 W Georgia St, Vancouver, BC",
    address_components: {
      street_number: "590",
      route: "W Georgia St",
      locality: "Vancouver",
      administrative_area_level_1: "BC",
      postal_code: null,
      country: "CA",
    },
    geometry: { location: { lat: 49.2814683, lng: -123.117244 } },
    formatted_phone_number: null,
    international_phone_number: null,
    website: "https://www.glowbalgroup.com/glowbal/",
    types: PLACE_TYPES_RESTAURANT_BAR,
    business_status: "OPERATIONAL",
    price_level: null,
    rating: null,
    user_ratings_total: null,
    opening_hours: { weekday_text: [] },
    photos: [
      {
        url: "https://www.glowbalgroup.com/img/glow-img/resto-gallery/img1.jpg",
        credit_name: "Glowbal",
        credit_url: "https://www.glowbalgroup.com/glowbal/",
        source: "official_website",
      },
      {
        url: "https://www.glowbalgroup.com/img/glow-img/food-gallery/img1.jpg",
        credit_name: "Glowbal",
        credit_url: "https://www.glowbalgroup.com/glowbal/",
        source: "official_website",
      },
    ],
    cover_image: {
      url: "https://www.glowbalgroup.com/img/glow-img/resto-gallery/img2.jpg",
      credit_name: "Glowbal",
      credit_url: "https://www.glowbalgroup.com/glowbal/",
      source: "official_website",
    },
    happy_hour: {
      days: [0, 1, 2, 3, 4, 5, 6],
      start: "14:00",
      end: "17:00",
      verified: true,
      verified_source: "https://www.glowbalgroup.com/glowbal/",
      deals: [
        { name: "Beer", price: "$6", category: "drink", description: "" },
        { name: "Wine", price: "$6–9.50", category: "drink", description: "" },
        { name: "Cocktails", price: "$10–12", category: "drink", description: "" },
        { name: "Oysters", price: "$2.50 ea", category: "food", description: "" },
        { name: "Market vegetables", price: "$10", category: "food", description: "" },
        { name: "Calamari", price: "$14", category: "food", description: "" },
      ],
    },
    // Amenities: outdoor_seating/gluten_free_options/wheelchair_accessible_entrance
    // are verified where true, otherwise null (unconfirmed, not guessed).
    // transit is computed from real SkyTrain station coordinates vs this
    // venue's geometry — not a Places field, our own addition.
    amenities: {
      outdoor_seating: true,
      gluten_free_options: null,
      wheelchair_accessible_entrance: null,
      parking: null,
      transit: {
        nearest_station: "Granville",
        distance_m: 148,
        walkable: true
      }
    },
    data_source: "manual",
    last_synced_at: null,
  },
{
  id: "central-restaurants-vancouver-bentall",
  place_id: null,
  name: "Central Restaurants Vancouver - Bentall",
  formatted_address: "555 Burrard St #120, Vancouver, BC",
  address_components: {
    street_number: "555",
    route: "Burrard St",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V7X 1M8",
    country: "CA",
  },
  geometry: { location: { lat: 49.2863381, lng: -123.1190948 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://centralrestaurants.ca/locations/vancouver-bentall",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://images.squarespace-cdn.com/content/v1/61bbefc477d8c050a7f13059/1741382492206-HS2SQSZ4AJ895FRALKVV/Central+Restaurants.jpg",
    credit_name: "Central Restaurants Vancouver - Bentall",
    credit_url: "https://centralrestaurants.ca/locations/vancouver-bentall",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "14:00",
    end: "17:00",
    verified: true,
    verified_source: "https://centralrestaurants.ca/vancouver-bentall/menu",
    deals: [
      { name: "Cheeseburger Slider (min 2)", price: "$4", category: "food", description: "Also happy hour daily 9pm-close" },
      { name: "Baba's Cheddar Perogies (4pc)", price: "$5", category: "food", description: "" },
      { name: "Spicy California Roll (4pc)", price: "$5", category: "food", description: "" },
      { name: "Tableside Dressed Truffle Fries", price: "$11", category: "food", description: "" },
      { name: "Highballs (1oz)", price: "$5", category: "drink", description: "" },
      { name: "House Beer", price: "$5.50", category: "drink", description: "" },
      { name: "House Wine (7oz)", price: "$7", category: "drink", description: "" },
      { name: "Espresso Martini (2oz)", price: "$9", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: null,
    wheelchair_accessible_entrance: true,
    parking: null,
    transit: {
        nearest_station: "Burrard",
        distance_m: 125,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "tap-barrel-convention-centre",
  place_id: null,
  name: "Tap & Barrel (Convention Centre)",
  formatted_address: "1055 Canada Place, Unit 76, Vancouver, BC",
  address_components: {
    street_number: "1055",
    route: "Canada Place",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6C 0C3",
    country: "CA",
  },
  geometry: { location: { lat: 49.2896385, lng: -123.1170959 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://tapandbarrel.com/locations/tap-barrel-convention-centre/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://tapandbarrel.com/wp-content/uploads/2021/04/024-scaled.jpg",
    credit_name: "Tap & Barrel",
    credit_url: "https://tapandbarrel.com/locations/tap-barrel-convention-centre/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "14:00",
    end: "17:30",
    verified: true,
    verified_source: "https://tapandbarrel.com/wp-content/uploads/2026/04/Convention-Centre-Food-Menu.pdf",
    deals: [
      { name: "Tots or Fries", price: "$5", category: "food", description: "Also happy hour daily 9pm-close" },
      { name: "Famous Fried Pickles", price: "$9.50", category: "food", description: "" },
      { name: "Gyoza", price: "$10", category: "food", description: "" },
      { name: "Truffle Waffle Fries", price: "$8", category: "food", description: "" },
      { name: "Well Highballs (1oz)", price: "$5", category: "drink", description: "" },
      { name: "LOLO Tequila Paloma Fizz (1oz)", price: "$7", category: "drink", description: "" },
      { name: "Classic Margarita (2oz)", price: "$10", category: "drink", description: "" },
      { name: "Stone Road White or Red (6oz)", price: "$6", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Burrard",
        distance_m: 509,
        walkable: false,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "p2b-restaurant-bar",
  place_id: null,
  name: "P2B Restaurant & Bar",
  formatted_address: "1133 W Hastings St, Vancouver, BC",
  address_components: {
    street_number: "1133",
    route: "W Hastings St",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6E 3T3",
    country: "CA",
  },
  geometry: { location: { lat: 49.2885171, lng: -123.1207242 } },
  formatted_phone_number: "604.691.2777",
  international_phone_number: null,
  website: "https://www.p2bbistro.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://images.squarespace-cdn.com/content/v1/6848a0f1f98a1d23a296d959/c4cec63e-252f-41f0-8364-b5c964373533/Photo+2021-03-22%2C+1+59+21+PM.jpg",
    credit_name: "P2B Restaurant & Bar",
    credit_url: "https://www.p2bbistro.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://www.p2bbistro.com/happyhour",
    deals: [
      { name: "Sea Salt Fries & Dip", price: "$6", category: "food", description: "" },
      { name: "Hummus Dip + Flat Bread", price: "$9", category: "food", description: "" },
      { name: "Gyozas & Greens", price: "$10", category: "food", description: "" },
      { name: "Wings & Fried Pickle Chips", price: "$13", category: "food", description: "" },
      { name: "Highballs (1oz)", price: "$6", category: "drink", description: "" },
      { name: "House Draft Beer (14oz)", price: "$6", category: "drink", description: "" },
      { name: "House Red or White Wine (5oz)", price: "$7", category: "drink", description: "" },
      { name: "Espresso Martini (2oz)", price: "$12", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Burrard",
        distance_m: 325,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "relish-the-pub",
  place_id: null,
  name: "Relish The Pub",
  formatted_address: "888 Nelson St, Vancouver, BC",
  address_components: {
    street_number: "888",
    route: "Nelson St",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6Z 2S1",
    country: "CA",
  },
  geometry: { location: { lat: 49.2799730, lng: -123.1252527 } },
  formatted_phone_number: "604-669-1962",
  international_phone_number: null,
  website: "https://www.relishthepub.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://static.wixstatic.com/media/d4cdc4_23853c3b3f6849a29c8a13d653981803~mv2.jpg/v1/fill/w_719,h_496,al_c,q_80,enc_avif,quality_auto/patio%20at%20night.jpg",
    credit_name: "Relish The Pub",
    credit_url: "https://www.relishthepub.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "14:00",
    end: "18:00",
    verified: true,
    verified_source: "https://www.relishthepub.com/_files/ugd/d4cdc4_4af3aaf831a140ff86a15c5f2163c3b2.pdf",
    deals: [
      { name: "Poutine", price: "$7.50", category: "food", description: "Seasoned kennebec potatoes, brown gravy, squeaky cheese curds" },
      { name: "Spicy Garlic Prawns", price: "$9.50", category: "food", description: "Baked skillet prawns, garlic herb butter, sambal oelek" },
      { name: "Caesar Salad", price: "$7.50", category: "food", description: "" },
      { name: "Chicken Wings", price: "$7.50", category: "food", description: "Choice of buffalo, jerk, Korean BBQ, and more" },
      { name: "Dry Ribs", price: "$6.50", category: "food", description: "" },
      { name: "Yam Fries", price: "$8", category: "food", description: "Served with chipotle aioli" },
      { name: "All Highballs", price: "$6", category: "drink", description: "" },
      { name: "Red Truck (Lager or Ale)", price: "$6.25", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Granville",
        distance_m: 448,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "french-creek-pub-vancouver",
  place_id: null,
  name: "French Creek Pub (Vancouver - Burrard)",
  formatted_address: "1100 Burrard St #101, Vancouver, BC",
  address_components: {
    street_number: "1100",
    route: "Burrard St",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6Z 1Y9",
    country: "CA",
  },
  geometry: { location: { lat: 49.2797579, lng: -123.1277323 } },
  formatted_phone_number: "604-559-0444",
  international_phone_number: null,
  website: "https://frenchcreekpub.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://frenchcreekpub.com/wp-content/uploads/2025/02/QWkbVA5NRE6YmOy9sq9Wrg-scaled.jpeg",
    credit_name: "French Creek Pub",
    credit_url: "https://frenchcreekpub.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "17:00",
    verified: true,
    verified_source: "https://frenchcreekpub.com/menus/",
    deals: [
      { name: "Half Price Wings", price: "50% off", category: "food", description: "Monday & Tuesday, all day" },
      { name: "All Day Happy Hour", price: "N/A", category: "food", description: "Thursday: standard happy hour menu available all day instead of just 3-5pm" },
      { name: "Fish & Chips (meal only)", price: "10% off", category: "food", description: "Friday special" },
      { name: "Fish Bowl Cocktails", price: "10% off", category: "drink", description: "Friday special" },
      { name: "Goodie Baskets", price: "10% off", category: "food", description: "Saturday special" },
      { name: "Fisherman's Shaft", price: "$9.50", category: "drink", description: "Saturday special; house vodka, Kahlua, creme de cacao, Bailey's, cold brew" },
      { name: "Party Boat Special", price: "$110", category: "food", description: "Sunday only (regular menu price $119)" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Granville",
        distance_m: 606,
        walkable: false,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "zubu-ramen-downtown",
  place_id: null,
  name: "ZUBU Ramen (Downtown)",
  formatted_address: "869 Hornby St, Vancouver, BC V6Z 1T9",
  address_components: {
    street_number: "869",
    route: "Hornby Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6Z 1T9",
    country: "CA",
  },
  geometry: { location: { lat: 49.2810, lng: -123.1222 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://byzubu.com/ramen/menu/downtown-menu/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://byzubu.com/wp-content/uploads/2024/03/Tonkotsu-Ramen-1-500x500.jpg",
    credit_name: "ZUBU Ramen",
    credit_url: "https://byzubu.com/ramen/menu/downtown-menu/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4],
    start: "14:00",
    end: "17:00",
    verified: true,
    verified_source: "https://byzubu.com/ramen/menu/downtown-menu/",
    deals: [
      { name: "Selected Ramen & Rice Bowl", price: "$16.95", category: "food", description: "Sunday-Thursday, 2-5pm & again 9pm-close" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Granville",
        distance_m: 218,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "1931-gallery-bistro",
  place_id: null,
  name: "1931 Gallery Bistro",
  formatted_address: "750 Hornby Street, Vancouver, BC",
  address_components: {
    street_number: "750",
    route: "Hornby Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6Z 2H7",
    country: "CA",
  },
  geometry: { location: { lat: 49.282978, lng: -123.120203 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://www.1931gallerybistro.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://images.squarespace-cdn.com/content/v1/5dc1bdb783f2693cda09997b/1601975794161-8RQ85V4JPXB1RL1PKDW7/AboutUs.jpg",
    credit_name: "1931 Gallery Bistro",
    credit_url: "https://www.1931gallerybistro.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "14:00",
    end: "17:00",
    verified: true,
    verified_source: "https://www.1931gallerybistro.com/happyhour-1",
    deals: [
      { name: "Marinated Olives", price: "$9", category: "food", description: "" },
      { name: "Wagyu Beef Carpaccio", price: "$17", category: "food", description: "" },
      { name: "Charcuterie Board", price: "$26", category: "food", description: "" },
      { name: "Provence Highball", price: "$10", category: "drink", description: "House cocktail" },
      { name: "Here's Looking At You, Kid", price: "$14", category: "drink", description: "House cocktail" },
      { name: "Granville Island Brewing Lager", price: "$6.50", category: "drink", description: "16oz glass" },
      { name: "Wine bottles", price: "20% off", category: "drink", description: "20% off all bottles during happy hour" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Granville",
        distance_m: 47,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "parker-rooftop",
  place_id: null,
  name: "Parker Rooftop",
  formatted_address: "1379 Howe Street, Vancouver, BC",
  address_components: {
    street_number: "1379",
    route: "Howe Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6Z 1R7",
    country: "CA",
  },
  geometry: { location: { lat: 49.27615, lng: -123.130196 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://www.parkerrooftop.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://images.squarespace-cdn.com/content/v1/658f1f036aef955f1fcb9274/11536bb8-32ba-451c-b3a3-b8014fe7f3f8/DSC08847.jpg",
    credit_name: "Parker Rooftop",
    credit_url: "https://www.parkerrooftop.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://www.parkerrooftop.com/s/Parker-HH-April-28-2026.pdf",
    deals: [
      { name: "Chicken Karaage", price: "$15", category: "food", description: "crispy fried chicken, lemon wedge" },
      { name: "Shrimp Tempura", price: "$18", category: "food", description: "creamy spicy sauce, crisp herbs" },
      { name: "Truffle Fries", price: "$10", category: "food", description: "black truffle, grana padano, thyme" },
      { name: "Parker Sliders", price: "$15", category: "food", description: "confit garlic aioli, iceberg lettuce, pickles" },
      { name: "Spicy Tuna Crispy Rice", price: "$18", category: "food", description: "nori, scallion" },
      { name: "Happy Hour Feature Cocktail", price: "$9", category: "drink", description: "1oz" },
      { name: "Draught Beer", price: "$7", category: "drink", description: "16oz" },
      { name: "50% Off Wine Bottles (up to $500)", price: "50% off", category: "drink", description: "Wednesdays only" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: "valet ($22)",
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 657,
        walkable: false,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "notch8-restaurant-bar",
  place_id: null,
  name: "Notch8 Restaurant & Bar",
  formatted_address: "900 West Georgia Street, Vancouver, BC",
  address_components: {
    street_number: "900",
    route: "West Georgia Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6C 2W6",
    country: "CA",
  },
  geometry: { location: { lat: 49.283839, lng: -123.120959 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://www.notch8-dining.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://m.ahstatic.com/is/image/accorhotels/aja_p_7171-76:8by10",
    credit_name: "Fairmont Hotel Vancouver - Notch8",
    credit_url: "https://www.fairmont.com/en/hotels/vancouver/fairmont-hotel-vancouver/dining/notch8.restaurant.html",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4],
    start: "15:00",
    end: "17:30",
    verified: true,
    verified_source: "https://www.notch8-dining.com/menus/",
    deals: [
      { name: "Charcuterie & Cheese", price: "25% off (reg. $30)", category: "food", description: "house pickled vegetables, marinated olives, grainy mustard, tomato jam" },
      { name: "West Coast Oysters (each)", price: "25% off (reg. $4.50)", category: "food", description: "port mignonette, smoked cocktail sauce" },
      { name: "Black Kale", price: "25% off (reg. $22)", category: "food", description: "pine nuts, grana padano, buttermilk garlic & anchovy dressing" },
      { name: "Notch8 Burger", price: "25% off (reg. $29)", category: "food", description: "smoked mustard aioli, cheddar, smoked bacon, onion jam" },
      { name: "Girolles Flatbread", price: "25% off (reg. $25)", category: "food", description: "chanterelle mushroom, café de Paris butter" },
      { name: "Featured Wine Selection", price: "varies", category: "drink", description: "Rotating selection of specially featured wines during happy hour" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: "paid",
    transit: {
        nearest_station: "Granville",
        distance_m: 128,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "hawksworth-restaurant",
  place_id: null,
  name: "Hawksworth Restaurant",
  formatted_address: "801 West Georgia Street, Vancouver, BC",
  address_components: {
    street_number: "801",
    route: "West Georgia Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6C 1P7",
    country: "CA",
  },
  geometry: { location: { lat: 49.2834389, lng: -123.1189111 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://hawksworthrestaurant.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://hawksworthrestaurant.com/wp-content/uploads/2025/05/Sablefish-sunchoke-kimchiapple-bacon-citrusmustard-1080x722.jpg",
    credit_name: "Hawksworth Restaurant",
    credit_url: "https://hawksworthrestaurant.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "16:00",
    end: "18:00",
    verified: true,
    verified_source: "https://hawksworthrestaurant.com/wp-content/uploads/2026/05/Features-May-15-2026.pdf",
    deals: [
      { name: "Freshly Shucked Oysters", price: "$2 each", category: "food", description: "mignonette, cocktail sauce" },
      { name: "Steak Tartare", price: "$16", category: "food", description: "mustard, cornichon, cured yolk, potato chip" },
      { name: "'KFC' (Korean Fried Cauliflower)", price: "$10", category: "food", description: "sesame" },
      { name: "Three Cheese Platter", price: "$15", category: "food", description: "candied fig, pear compote, marcona almond" },
      { name: "Truffle Fries", price: "$12", category: "food", description: "parmesan, chives" },
      { name: "Negroni", price: "$11", category: "drink", description: "tanqueray, cinzano rosso, campari, 2.5oz" },
      { name: "Daiquiri", price: "$10", category: "drink", description: "havana club 3yr, lime juice, simple syrup, 2oz" },
      { name: "Hawksworth \"Georgia\" Lager", price: "$7", category: "drink", description: "North Point Brewing Co., 355ml" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: "valet (at Rosewood Hotel Georgia)",
    transit: {
        nearest_station: "Vancouver City Centre",
        distance_m: 83,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "banter-room",
  place_id: null,
  name: "Banter Room",
  formatted_address: "1039 Mainland Street, Vancouver, BC",
  address_components: {
    street_number: "1039",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: null,
    country: "CA",
  },
  geometry: { location: { lat: 49.276318, lng: -123.119740 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://banterroom.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://images.squarespace-cdn.com/content/v1/58c071995016e1df4b7ead5f/1a7d95f7-f238-450e-8b84-07cd5cb7f425/BanterRoom-Nov2025-NoraHamade-08725+.jpg",
    credit_name: "Banter Room",
    credit_url: "https://banterroom.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "14:00",
    end: "17:00",
    verified: true,
    verified_source: "https://banterroom.com/menu",
    deals: [
      { name: "Tacos (chicken, prawn or carne asada)", price: "$7", category: "food", description: "Served as singles" },
      { name: "Roasted Beet Hummus", price: "$14", category: "food", description: "" },
      { name: "Crispy Tiger Prawns", price: "$14", category: "food", description: "" },
      { name: "Smash Buddy", price: "$8", category: "food", description: "" },
      { name: "Banter Lager / Russell Pale Ale", price: "$6", category: "drink", description: "" },
      { name: "House Red, White & Rosé (6oz)", price: "$9", category: "drink", description: "" },
      { name: "Tequila Soda & Slush", price: "$11", category: "drink", description: "" },
      { name: "Espresso Martini", price: "$12", category: "drink", description: "Ketel One Vodka, Kahlua, cold brew coffee, simple syrup" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 262,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "el-guapo-mexican-restaurant",
  place_id: null,
  name: "El Guapo",
  formatted_address: "1009 Hamilton Street, Vancouver, BC",
  address_components: {
    street_number: "1009",
    route: "Hamilton Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6B 5T4",
    country: "CA",
  },
  geometry: { location: { lat: 49.276758, lng: -123.120146 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://elguapo.ca/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://elguapo.ca/assets/content/margarita.jpg",
    credit_name: "El Guapo",
    credit_url: "https://elguapo.ca/",
    source: "official_website",
  },
  happy_hour: {
    days: [1, 2, 3, 4],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://elguapo.ca/assets/content/el-guapo-2025-happy-hour.webp",
    deals: [
      { name: "Guacamole", price: "$12", category: "food", description: "Topped with feta, crispy carrots, served with corn chips" },
      { name: "Tacos (Al Pastor, Carnitas, or Crispy Cauliflower)", price: "$7", category: "food", description: "" },
      { name: "Chicken Wings", price: "$15", category: "food", description: "10 crispy fried chicken wings, topped with jalapeños, served with salsa borracha" },
      { name: "Nachos", price: "$15", category: "food", description: "Fried corn chips, house cheese sauce, Monterey Jack, jalapeños, pico de gallo, feta & green onion" },
      { name: "Classic Lime Margarita", price: "$12", category: "drink", description: "" },
      { name: "Guapo Lager", price: "$5", category: "drink", description: "" },
      { name: "Stella Artois", price: "$7", category: "drink", description: "" },
      { name: "House Wine", price: "$7", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 293,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "tacofino-taco-bar-yaletown",
  place_id: null,
  name: "Tacofino Yaletown Burrito Bar",
  formatted_address: "1025 Mainland Street, Vancouver, BC",
  address_components: {
    street_number: "1025",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6B 2R9",
    country: "CA",
  },
  geometry: { location: { lat: 49.276445, lng: -123.119515 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://www.tacofino.com/location/yaletown-burrito-bar",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://images.squarespace-cdn.com/content/v1/696559eeb2270933e9839fd5/5a6b9547-78eb-4673-956a-f8c4806cc7b9/Yaletown-11.png",
    credit_name: "Tacofino",
    credit_url: "https://www.tacofino.com/locations",
    source: "official_website",
  },
  happy_hour: {
    days: [1, 2, 3, 4, 5],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://www.facebook.com/tacofinolovesyou/posts/tacofino-happy-hour-instant-mood-booster-join-us-every-monday-friday-from-3-6-pm/1016478513816229/",
    deals: [
      { name: "Happy Hour Food (any item)", price: "$10", category: "food", description: "Applies to select happy hour food items, per Tacofino's own Facebook post; itemized menu not published on tacofino.com" },
      { name: "Happy Hour Drinks (any item)", price: "$10", category: "drink", description: "Applies to select happy hour drink items, per Tacofino's own Facebook post; itemized menu not published on tacofino.com" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 282,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "the-greek-by-anatoli-yaletown",
  place_id: null,
  name: "The Greek by Anatoli — Yaletown",
  formatted_address: "1043 Mainland Street, Vancouver, BC",
  address_components: {
    street_number: "1043",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: null,
    country: "CA",
  },
  geometry: { location: { lat: 49.276224, lng: -123.119866 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://www.thegreekbyanatoli.com/yaletown",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://www.thegreekbyanatoli.com/assets/images/catering/catering-greek-salad.jpg",
    credit_name: "The Greek by Anatoli",
    credit_url: "https://www.thegreekbyanatoli.com/yaletown",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "14:00",
    end: "17:00",
    verified: true,
    verified_source: "https://www.thegreekbyanatoli.com/yaletown-menu",
    deals: [
      { name: "Hummus (V)", price: "$11", category: "food", description: "" },
      { name: "Greek Salad (GF)", price: "$15", category: "food", description: "" },
      { name: "Keftedes (GF)", price: "$8", category: "food", description: "" },
      { name: "Calamari", price: "$13", category: "food", description: "" },
      { name: "Parallel 49 House Lager (20oz)", price: "$7", category: "drink", description: "" },
      { name: "Helen's Sangria (5oz)", price: "$8", category: "drink", description: "" },
      { name: "Aperol Spritz (5oz)", price: "$12", category: "drink", description: "" },
      { name: "Glass of House Wine (5oz)", price: "$9", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 248,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "the-parlour",
  place_id: null,
  name: "The Parlour",
  formatted_address: "1011 Hamilton Street, Vancouver, BC",
  address_components: {
    street_number: "1011",
    route: "Hamilton Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6B 5T4",
    country: "CA",
  },
  geometry: { location: { lat: 49.276692, lng: -123.120266 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://theparlourrestaurants.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://theparlourrestaurants.com/wp-content/uploads/2017/05/pizza-grid-lft-1000x1600.jpg",
    credit_name: "The Parlour",
    credit_url: "https://theparlourrestaurants.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://theparlourrestaurants.com/vancouver-menu/#happy-hour",
    deals: [
      { name: "Meatball Mini", price: "$6", category: "food", description: "" },
      { name: "Lobster Roll", price: "$7", category: "food", description: "" },
      { name: "Belly Bite (GF)", price: "$6", category: "food", description: "" },
      { name: "Roasted Veg (GF)", price: "$12", category: "food", description: "" },
      { name: "House Margarita (2oz)", price: "$12", category: "drink", description: "" },
      { name: "Stella Artois (16oz)", price: "$8", category: "drink", description: "" },
      { name: "Tippy Canoe Lager (16oz)", price: "$6.75", category: "drink", description: "By Granville Island" },
      { name: "Highballs", price: "$7.75", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 283,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "the-flying-pig-yaletown",
  place_id: null,
  name: "The Flying Pig (Yaletown)",
  formatted_address: "1168 Hamilton St, Vancouver, BC",
  address_components: {
    street_number: "1168",
    route: "Hamilton Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: null,
    country: "CA",
  },
  geometry: { location: { lat: 49.275021, lng: -123.121989 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://theflyingpigvan.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://www.theflyingpigvan.com/wp-content/uploads/2018/04/TFP__0001_0E5A9985.jpg",
    credit_name: "The Flying Pig",
    credit_url: "https://theflyingpigvan.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://theflyingpigvan.com/menu/",
    deals: [
      { name: "Warm Castelvetrano Olives", price: "$8.75", category: "food", description: "Toasted fennel, chili + garlic" },
      { name: "Parmesan Truffle Fries", price: "$9.75", category: "food", description: "Hand-cut fries, truffle oil, shaved parmesan, garlic aioli" },
      { name: "Braised Meatballs", price: "$13.50", category: "food", description: "Tomato fondue, grilled focaccia" },
      { name: "PEI Mussels + Fries", price: "$19.50", category: "food", description: "White wine, tomato + fennel broth, grilled focaccia" },
      { name: "TFP Lager", price: "$5.75", category: "drink", description: "Russell Brewing, 16oz" },
      { name: "TFP Pale Ale", price: "$5.75", category: "drink", description: "Russell Brewing, 16oz" },
      { name: "Highballs", price: "$6.50", category: "drink", description: "Premium selection, 1oz" },
      { name: "Sparkling Rosé", price: "$9.50", category: "drink", description: "Narrative 'XC', 5oz" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 85,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "the-keg-steakhouse-bar-yaletown",
  place_id: null,
  name: "The Keg Steakhouse + Bar (Yaletown)",
  formatted_address: "1011 Mainland Street, Vancouver, BC V6B 5P9",
  address_components: {
    street_number: "1011",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6B 5P9",
    country: "CA",
  },
  geometry: { location: { lat: 49.276648, lng: -123.119445 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://thekeg.com/en/locations/yaletown",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://cdn.sanity.io/images/dw0heewu/production/0cd7a88b7e1bbb0f0281e4aa10ef4c8390f2fb54-650x350.jpg?auto=format",
    credit_name: "The Keg Steakhouse + Bar (Yaletown)",
    credit_url: "https://thekeg.com/en/locations/yaletown",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "16:00",
    end: "18:00",
    verified: true,
    verified_source: "https://thekeg.com/en/locations/yaletown/menu",
    deals: [
      { name: "Prime Rib Sliders", price: "$7 each", category: "food", description: "Freshly shaved, horseradish dijon, red wine herb jus" },
      { name: "Truffle Fries", price: "$8", category: "food", description: "" },
      { name: "Three Pepper Wings", price: "$15", category: "food", description: "Blue cheese crumble, pickled celery, blue cheese dressing" },
      { name: "Keg Burger", price: "$21", category: "food", description: "Lettuce, keg burger sauce, pickles, white cheddar, caramelized onion, fries or side salad" },
      { name: "The Keg Caesar", price: "$7", category: "drink", description: "1oz" },
      { name: "The Keg Old Fashioned", price: "$11", category: "drink", description: "2oz" },
      { name: "Aperol Spritz", price: "$11", category: "drink", description: "5oz" },
      { name: "Espresso Martini", price: "$12", category: "drink", description: "2oz" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: true,
    wheelchair_accessible_entrance: true,
    parking: "street",
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 304,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "earls-yaletown",
  place_id: null,
  name: "Earls Yaletown",
  formatted_address: "1095 Mainland Street, Vancouver, BC",
  address_components: {
    street_number: "1095",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: null,
    country: "CA",
  },
  geometry: { location: { lat: 49.275779, lng: -123.120525 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://earls.ca/locations/yaletown/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://earls.ca/wp-content/uploads/2025/03/yaletown-header-retina.png__2000x0_crop-smart_subsampling-2_upscale.png",
    credit_name: "Earls Yaletown",
    credit_url: "https://earls.ca/locations/yaletown/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://earls.ca/locations/yaletown/menu/happy-hour/",
    deals: [
      { name: "Truffle Fries", price: "$7", category: "food", description: "Peppercorn melange, white truffle aioli, parmesan" },
      { name: "Queen Bee Pizza", price: "$20", category: "food", description: "Spicy capicola, hot honey, chorizo, mozzarella" },
      { name: "Petite Steak Frites", price: "$16", category: "food", description: "Gluten free" },
      { name: "Nashville Crispy Chicken + Pickle Skewers", price: "$13", category: "food", description: "Happy hour exclusive" },
      { name: "Aperol Spritz", price: "1/2 price", category: "drink", description: "3.5oz" },
      { name: "Nitro Espresso Martini", price: "1/2 price", category: "drink", description: "2oz" },
      { name: "Sangria", price: "1/2 price", category: "drink", description: "7oz, red or white" },
      { name: "Earls Lime Margarita", price: "1/2 price", category: "drink", description: "1.5oz" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 182,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "moltaqa-moroccan-restaurant",
  place_id: null,
  name: "Moltaqa Moroccan Restaurant",
  formatted_address: "1002 Mainland St, Vancouver, BC V6B 6J8",
  address_components: {
    street_number: "1002",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6B 6J8",
    country: "CA",
  },
  geometry: { location: { lat: 49.276436, lng: -123.119045 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://moltaqarestaurant.ca/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://moltaqarestaurant.ca/wp-content/uploads/2026/04/duck-halal-food-e1777383539714.webp",
    credit_name: "Moltaqa Moroccan Restaurant",
    credit_url: "https://moltaqarestaurant.ca/",
    source: "official_website",
  },
  happy_hour: {
    days: [1, 2, 3, 4, 5],
    start: "15:00",
    end: "17:00",
    verified: true,
    verified_source: "https://moltaqarestaurant.ca/menu/",
    deals: [
      { name: "Lamb Merguez Sausage", price: "$6", category: "food", description: "Hand-rolled halal lamb sausage with Moroccan spices" },
      { name: "Beef Kofta Meatballs (3 pcs)", price: "$8", category: "food", description: "Moroccan spiced halal beef meatballs" },
      { name: "Hummus", price: "$8", category: "food", description: "Creamy chickpea hummus with warm Moroccan bread" },
      { name: "Beef Briwat", price: "$5", category: "food", description: "Crispy Moroccan pastry filled with spiced beef" },
      { name: "Moroccan Cocktails", price: "$11", category: "drink", description: "2oz, signature Moroccan-inspired cocktails" },
      { name: "Moroccan Mint Tea", price: "$4", category: "drink", description: "Traditional Moroccan gunpowder green tea with fresh mint" },
      { name: "House Wine", price: "$8", category: "drink", description: "5oz" },
      { name: "Local Beer", price: "$7", category: "drink", description: "Selection of local Vancouver craft beers" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 301,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "alchemy-bar-kitchen",
  place_id: null,
  name: "Alchemy Bar & Kitchen",
  formatted_address: "1269 Hamilton St, Vancouver, BC",
  address_components: {
    street_number: "1269",
    route: "Hamilton Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: null,
    country: "CA",
  },
  geometry: { location: { lat: 49.274234, lng: -123.123941 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://www.alchemybar-kitchen.ca/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://www.alchemybar-kitchen.ca/images/ALCHEMY5.jpg",
    credit_name: "Alchemy Bar & Kitchen",
    credit_url: "https://www.alchemybar-kitchen.ca/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://www.alchemybar-kitchen.ca/happyhour.html",
    deals: [
      { name: "Chicken Wings", price: "$16.95", category: "food", description: "House-made marinated wings: hot, S&P, lemon pepper, honey garlic, or BBQ" },
      { name: "Cheesy Spinach & Artichoke Dip", price: "$15.95", category: "food", description: "Spinach, artichokes, cheese, served with tortilla chips" },
      { name: "Prawn & Parmesan Arancini", price: "$17.95", category: "food", description: "3 crispy risotto balls with mozzarella, topped with garlic lemon prawns" },
      { name: "Margherita Pizza", price: "$19.95", category: "food", description: "Tomato sauce, mozzarella, cherry tomato, bocconcini, herbs, Grana Padano" },
      { name: "Classic Margarita", price: "$10", category: "drink", description: "" },
      { name: "Aperol Spritz", price: "$11", category: "drink", description: "" },
      { name: "Espresso Martini", price: "$13", category: "drink", description: "" },
      { name: "Rotating Tap Beer", price: "$6.50", category: "drink", description: "" },
    ],
  },
  amenities: {
    outdoor_seating: null,
    gluten_free_options: null,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 170,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
{
  id: "yaletown-brewing-company",
  place_id: null,
  name: "Yaletown Brewing Company",
  formatted_address: "1111 Mainland St, Vancouver, BC V6B 2T9",
  address_components: {
    street_number: "1111",
    route: "Mainland Street",
    locality: "Vancouver",
    administrative_area_level_1: "BC",
    postal_code: "V6B 2T9",
    country: "CA",
  },
  geometry: { location: { lat: 49.275555, lng: -123.120860 } },
  formatted_phone_number: null,
  international_phone_number: null,
  website: "https://yaletownbrewing.com/",
  types: PLACE_TYPES_RESTAURANT_BAR,
  business_status: "OPERATIONAL",
  price_level: null,
  rating: null,
  user_ratings_total: null,
  opening_hours: { weekday_text: [] },
  photos: [],
  cover_image: {
    url: "https://yaletownbrewing.com/wp-content/uploads/2023/09/YaletownBrw_124-HDR_preview.jpeg",
    credit_name: "Yaletown Brewing Co.",
    credit_url: "https://yaletownbrewing.com/",
    source: "official_website",
  },
  happy_hour: {
    days: [0, 1, 2, 3, 4, 5, 6],
    start: "15:00",
    end: "18:00",
    verified: true,
    verified_source: "https://yaletownbrewing.com/wp-content/uploads/2025/08/YBC-Happy-Hour.pdf",
    deals: [
      { name: "Beer Pretzels", price: "$11", category: "food", description: "House made German style soft beer pretzels with grainy mustard" },
      { name: "Yaletown Poutine", price: "$15", category: "food", description: "House made beef and shallot gravy, melted cheese curds" },
      { name: "Gochujang Cauliflower", price: "$14", category: "food", description: "Korean fried cauliflower tossed in sweet and spicy chili sauce" },
      { name: "Fish Tacos", price: "$17", category: "food", description: "Crispy local pacific cod, marinated coleslaw, salsa, avocado purée" },
      { name: "Fresh Beer", price: "$6", category: "drink", description: "16oz — 604 Lager, Loading Bay IPA, Roundhouse Wheat, Yaletown Ale, or rotating seasonal" },
      { name: "House Wine", price: "$7", category: "drink", description: "6oz — Sumac Ridge Merlot or Jackson Triggs Sauvignon Blanc" },
      { name: "Aperol Spritz", price: "$12", category: "drink", description: "" },
      { name: "Margarita", price: "$11", category: "drink", description: "1.5oz Olmeca tequila, .5oz Cointreau, fresh lime juice" },
    ],
  },
  amenities: {
    outdoor_seating: true,
    gluten_free_options: true,
    wheelchair_accessible_entrance: null,
    parking: null,
    transit: {
        nearest_station: "Yaletown-Roundhouse",
        distance_m: 150,
        walkable: true,
      },
  },
  data_source: "manual",
  last_synced_at: null,
},
];
